# Generated by Django 4.0.6 on 2022-10-07 18:56

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên')),
            ],
            options={
                'verbose_name': 'loại',
                'verbose_name_plural': 'danh sách loại',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sự kiện')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='ảnh sự kiện')),
                ('start_time', models.DateField(default=datetime.date(2022, 10, 8), verbose_name='Ngày bắt đầu')),
                ('end_time', models.DateField(default=datetime.date(2022, 10, 8), verbose_name='Ngày kết thúc')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'sự kiện',
                'verbose_name_plural': 'danh sách sự kiện',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên bánh')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='Ản sản phẩm')),
                ('price', models.IntegerField(verbose_name='Đơn giá')),
                ('ingredient', models.CharField(default='Đang cập nhật', max_length=255, verbose_name='Các nguyên liệu')),
                ('describe', models.TextField(default='Đang cập nhật')),
                ('sale', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Mức giảm giá')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ManyToManyField(default=None, to='product.category')),
            ],
            options={
                'verbose_name': 'sản phẩm',
                'verbose_name_plural': 'danh sách sản phẩm',
            },
        ),
    ]
