# Generated by Django 4.0.6 on 2022-10-07 18:56

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('username', models.CharField(error_messages={'unique': 'Tài khoản người dùng đã tồn tại.'}, help_text='Yêu cầu 150 ký tự hoặc ít hơn. Ký tự, số và chỉ @/./+/-/_', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Tài khoản')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Địa chỉ email')),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[user.models.only_int, django.core.validators.MinLengthValidator(10)], verbose_name='Số điện thoại')),
                ('is_active', models.BooleanField(default=True, help_text='Chỉ định xem người dùng này có nên được coi là đang hoạt động hay không. Bỏ chọn mục này thay vì xóa tài khoản.', verbose_name='Hoạt động')),
                ('is_staff', models.BooleanField(default=False, help_text='Có thể đăng nhập vào trang quản lý', verbose_name='Nhân viên')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Quản trị viên')),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2022, 10, 7, 18, 56, 42, 232694, tzinfo=utc), verbose_name='ngày tham gia')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'khách hàng',
                'verbose_name_plural': 'danh sách khách hàng',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='đia chỉ')),
                ('status', models.IntegerField(default=0, help_text='0: Chờ xác nhận, 1: Đang giao:, 2:Đã giao, -1: Giao hàng thất bại', verbose_name='Trạng thái đơn hàng')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='ngày xuất hóa đơn')),
            ],
            options={
                'verbose_name': 'hóa đơn',
                'verbose_name_plural': 'danh sách hóa đơn',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1, verbose_name='Số sản phẩm')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Sản phẩm')),
            ],
            options={
                'verbose_name': 'chi tiết hóa đơn',
                'verbose_name_plural': 'danh sách chi tiết hóa đơn',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(through='user.OrderDetail', to='product.product', verbose_name='Chi tiết sản phẩm'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Khách hàng'),
        ),
    ]
